### ISSUE TITLE
ChromeStatus.com doesn't load in Microsoft Edge

### ISSUE THREAD

**Issue by jacobrossi** [GoogleChrome/chromium-dashboard#252]
Looks like a UA string sniffing issue. Switching to the Chrome UA string fixes. I'm using the latest stable version of Edge (13.10587).

![image](https://cloud.githubusercontent.com/assets/2118562/11798062/65f59e46-a27c-11e5-9e65-02b87437b32a.png)

**Comment by ebidel** [comment]
There's no UA sniffing. If that error happens, it comes from a failed promise from an xhr:
https://github.com/GoogleChrome/chromium-dashboard/blob/14754d7b442d5f0e2ca0964af8afcd431cf610f8/templates/features.html#L167

**Comment by ebidel** [comment]
@jacobrossi any ideas? Does Edge have `xhr.responseType='json'`? https://github.com/GoogleChrome/chromium-dashboard/blob/14754d7b442d5f0e2ca0964af8afcd431cf610f8/templates/features.html#L141

**Comment by jacobrossi** [comment]
Hmm...  but all I did was change the UA string in the dev tools to Chrome and things loaded. Nothing else in the platform changed.

**Comment by ebidel** [comment]
Are there console errors or anything?

**Comment by alrra** [comment]
> ![](https://cloud.githubusercontent.com/assets/2118562/11798062/65f59e46-a27c-11e5-9e65-02b87437b32a.png)

@ebidel This also sometimes happens in Firefox, especially on first load.  The problem seems to be due to _"empty"_ responses (e.g.: see [HAR file](https://github.com/GoogleChrome/chromium-dashboard/files/73945/1.har.zip) - `features.json - 0 bytes` ).

--

Or, another example (see: [HAR file](https://github.com/GoogleChrome/chromium-dashboard/files/73942/2.har.zip)):

![](https://cloud.githubusercontent.com/assets/1223565/12034667/ff71d730-ae3c-11e5-9069-e799186f155d.png)

**Comment by ebidel** [comment]
How do I repo?

**Comment by alrra** [comment]
> How do I repo?

@ebidel clear cache :arrow_right: visit chromestatus.com

--

Here is what I'm getting (had to hard refresh a few times until I got the content):

![](https://cloud.githubusercontent.com/assets/1223565/12043525/74d58f48-ae8e-11e5-807f-b02c755ce9e3.gif)

Note: I'm using Firefox 43.0.3 on OS X 10.11.2.

**Comment by jacobrossi** [comment]
I can confirm the same thing in Edge. Clearing cache and refreshing from server loads the site.  Maybe a server-side/CDN caching issue? Most likely changing the UA was just making it look like a new request and avoiding the cache or something.

**Comment by ebidel** [comment]
I'm not able to repo on FF 43, OS X 10.11.2. It could be a App Engine / certificate issue or something to do with the multiple redirect from chromestatus.com -> http://www.chromestatus.com/ -> https://www.chromestatus.com/features

**Comment by bledwards1** [comment]
In Edge, you cannot check to see if there are any console errors because it loads perfectly find with dev tools open (every single time). This is done by design.

The failure to load is caused by TypeError exception causing a Promise object to be rejected prematurely. 

The TypeError exception is thrown because 'console' object doesn't support method 'timeStamp' in normal mode (F12 Dev Tools closed). 

According to some of the documentation that was found, console.timeStamp is considered non-standard. It only works with full functionality in Chrome.

Reference: 
https://developer.mozilla.org/en-US/docs/Web/API/Console/timeStamp

"This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future."

**Comment by ebidel** [comment]
I've deployed the fix in https://github.com/GoogleChrome/chromium-dashboard/commit/fb54bed85511331c176183ae9b939c865afcec3a. Give it a try: https://www.chromestatus.com/features

**Comment by samccone** [comment]
ace research @bledwards1 :)

**Comment by bledwards1** [comment]
Looks good. Thank you @ebidel   Working well in builds 10586+ of Edge based on my testing. 

Thanks for the kudos, @samccone.

**Comment by alrra** [comment]
> > @ebidel This also sometimes happens in Firefox, especially on first load.

> I've deployed the fix in fb54bed. Give it a try: https://www.chromestatus.com/features

@ebidel I still encounter the issue in Firefox, and it seems [I'm not the only one](https://twitter.com/simevidas/status/704892313147994112) (Cc: @simevidas).

**Comment by ebidel** [comment]
See the reply :)
